declare module "eslint-plugin-compat" {}
declare module "eslint-plugin-import" {}
declare module "eslint-plugin-jsdoc" {}
declare module "eslint-plugin-n" {}
declare module "eslint-plugin-simple-import-sort" {}
declare module "eslint-plugin-unicorn" {}
declare module "eslint-plugin-jsx-a11y" {}
declare module "eslint-plugin-react" {}
declare module "eslint-plugin-react-hooks" {}
declare module "eslint-plugin-react-refresh" {}
declare module "eslint-plugin-jest" {}